 #11) მომხმარებელს შემოატანინეთ ორი რიცხვი შემდეგ კი ამ ორი რიცხვისგან შეადგინეთ ოთხი მათემატიკური მოქმედება, დამატება გამოკლება გამრავლება და გაყოფა
num1 = int(input("select any number: "))
num2 = int(input("select any number: "))
print(num1 + num2)
print(num1 - num2)
print(num2 - num1)
print(num1 * num2)
print(num1 / num2)
print(num2 / num1)
print(num1 % num2)
print(num2 % num1)
print(num1 ** num2)
print(num2 ** num1)